import React from "react";
import { Link } from "react-router-dom";

export function Privacy() {
  return <section className="hero heroCardStandard legalShell"><div className="heroBg heroBgBack" aria-hidden="true" /><div className="heroBg heroBgFront" aria-hidden="true" /><div className="legalScroller"><article className="legalPanel"><h1>Privacy</h1><p>Last updated September 26, 2026.</p><h2>Information we collect</h2><p>We collect information you provide for orders, accounts, contact requests, consignments, rewards, and optional marketing preferences. This may include your name, email, phone number, shipping and billing addresses, inventory records, and transaction history.</p><h2>How we use it</h2><p>We use this information to process and fulfill orders, prevent fraud and promotion abuse, provide customer support, maintain rewards and consignment records, and send communications you requested.</p><h2>Payments</h2><p>Card details are collected by Square. The Crystal Card Keep does not store full payment-card numbers.</p><h2>Sharing</h2><p>We share only what is needed with service providers that operate payments, hosting, email, shipping, fraud prevention, and required legal compliance. We do not sell personal information.</p><h2>Marketing choices</h2><p>Marketing email is optional. Every marketing message will provide an unsubscribe method. Transactional messages about an order may still be sent.</p><h2>Retention and requests</h2><p>We retain records as needed for fulfillment, accounting, fraud prevention, and legal obligations. To request access, correction, or deletion where applicable, contact chris.waldron319@thecrystalcardkeep.com.</p><p><Link className="btn" to="/policies">Store policies</Link></p></article></div></section>;
}

export function Terms() {
  return <section className="hero heroCardStandard legalShell"><div className="heroBg heroBgBack" aria-hidden="true" /><div className="heroBg heroBgFront" aria-hidden="true" /><div className="legalScroller"><article className="legalPanel"><h1>Terms of Sale</h1><p>Last updated September 26, 2026.</p><h2>Orders and payment</h2><p>An order is accepted when payment is successfully authorized and inventory is reserved. We may cancel and refund an order affected by an inventory error, pricing error, suspected fraud, or purchase-limit abuse.</p><h2>Product condition</h2><p>Singles are graded conservatively and material defects are disclosed. Factory-sealed products must remain sealed to qualify for an approved return unless the product arrived damaged or incorrect.</p><h2>Shipping</h2><p>Economy Letter is an optional untracked service for eligible low-value singles. By choosing it, the buyer accepts the increased delivery risk and lack of a carrier delivery scan. Tracked and oversized-order rules are disclosed at checkout.</p><h2>Promotions</h2><p>Welcome and rewards promotions are limited as stated. The first-purchase offer is single use per customer and limited to four qualifying redemptions per household. Creating duplicate accounts, identities, or addresses to repeat an offer is prohibited. Codes may be revoked when abuse is detected.</p><h2>Returns and disputes</h2><p>Contact us promptly about incorrect, damaged, or missing items. Photo or packaging evidence may be required. These terms do not limit rights that cannot legally be waived.</p><h2>Marketplace and consignment</h2><p>Marketplace and consignor features remain subject to separate written terms before public activation.</p><p><Link className="btn" to="/policies">Store policies</Link></p></article></div></section>;
}
